In [14]:
import numpy as np

In [15]:
arr = np.array([3,5,2,33,2,1,10,1])

In [16]:
np.mean(arr)

7.125

In [17]:
np.min(arr)

1

In [18]:
np.std(arr)

10.16658128379447

In [19]:
np.max(arr)

33

In [20]:
np.product(arr)

19800

In [21]:
np.var(arr)

103.359375

In [22]:
np.argmin(arr) #index of smallest no.

5

In [23]:
np.argmax(arr) #index of largest no.

3

In [24]:
np.unique(arr)

array([ 1,  2,  3,  5, 10, 33])

In [25]:
np.diff(arr)

array([  2,  -3,  31, -31,  -1,   9,  -9])

In [26]:
np.cumsum(arr)

array([ 3,  8, 10, 43, 45, 46, 56, 57])