In [18]:
import numpy as np
 
arr = np.array([[1, 2, 3], 
                [4, 5, 6], 
                [7, 8, 9]])
 
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [19]:
arr[0]

array([1, 2, 3])

In [20]:
arr[1] 

array([4, 5, 6])

In [21]:
# Accessing axis 1 (columns)
print("Column 0:", arr[:, 0])
print("Column 1:", arr[:, 1])
print("Column 2:", arr[:, 2])

Column 0: [1 4 7]
Column 1: [2 5 8]
Column 2: [3 6 9]


In [22]:
print("Row 0:", arr[0])
print("Row 1:", arr[1])
print("Row 2:", arr[2])

Row 0: [1 2 3]
Row 1: [4 5 6]
Row 2: [7 8 9]


In [23]:
np.sum(arr, axis=0)

array([12, 15, 18])

In [24]:
np.sum(arr, axis=1)

array([ 6, 15, 24])

In [25]:
arr[0][1]

2

In [26]:
arr[2][2]

9

In [27]:
arr[0,1]

2

In [28]:
arr[0:2, 1:3]

array([[2, 3],
       [5, 6]])

In [29]:
arr3D = np.array([[[1, 2, 3], [4, 5, 6]],
                  [[7, 8, 9], [10, 11, 12]]])

In [30]:
print(arr3D.shape) 

(2, 2, 3)


In [31]:
# First sheet, second row, third column
print(arr3D[0, 1, 2])  # Output: 6

6


In [32]:
print(arr3D[:, 0, :])   # Get the first row from both sheets

[[1 2 3]
 [7 8 9]]


In [33]:
print(arr3D[:,0,0])

[1 7]


In [34]:
arr3D[:,0,:] = 0
arr3D

array([[[ 0,  0,  0],
        [ 4,  5,  6]],

       [[ 0,  0,  0],
        [10, 11, 12]]])